# Generated by Django 3.1.7 on 2021-03-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_auto_20210308_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='setnum',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1),
            preserve_default=False,
        ),
    ]
