# Generated by Django 3.1.7 on 2021-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_set_setnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='setnum',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
