# Generated by Django 3.1.7 on 2021-03-08 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_auto_20210308_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'TR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
