# Generated by Django 3.1.7 on 2021-03-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0014_auto_20210308_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='setnum',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Set'),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.CharField(max_length=20),
        ),
    ]
