# Generated by Django 3.1.7 on 2021-03-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0018_setgroup_kaatsu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setgroup',
            name='kaatsu',
        ),
    ]
