# Generated by Django 3.1.7 on 2021-03-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0020_auto_20210314_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='bodypart',
            new_name='body_part',
        ),
    ]
