# Generated by Django 3.1.7 on 2021-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0022_auto_20210321_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(choices=[('LE', 'Legs'), ('AR', 'Arms'), ('BA', 'Back'), ('CH', 'Bhest'), ('SH', 'Shoulders'), ('CO', 'Core'), ('OT', 'Other')], max_length=2),
        ),
    ]
