# Generated by Django 3.1.7 on 2021-03-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0024_auto_20210323_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='setgroup',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
